[build]
  command = "pip install -r requirements.txt && bash netlify_deploy.sh"
  publish = "public"
  functions = "netlify/functions-build"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python run.py"
  port = 8872 