[build]
  command = "pip install -r requirements.txt && bash netlify_deploy.sh"
  publish = "public"
  functions = "netlify/functions-build"

[build.environment]
  PYTHON_VERSION = "3.11"
  PYTHON_MAJOR_VERSION = "3"
  PYTHON_MINOR_VERSION = "11"
  PYTHON_PATCH_VERSION = "8"
  PYTHON_MAJOR_MINOR_VERSION = "3.11"
  PYTHON_FULL_VERSION = "3.11.8"
  PYTHON_RUNTIME = "python3.11"
  PYTHON_BIN = "python3.11"
  PIP_BIN = "pip3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python run.py"
  port = 8872 